project_id = "dkrrfnpvqrpakngigxsb"

[functions.belvo-integration]
verify_jwt = true

[functions.request-email-change]
verify_jwt = true

[functions.confirm-email-change]
verify_jwt = false

[functions.autentique-signature]
verify_jwt = true

[functions.send-notification]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = true

[functions.spotify-metrics]
verify_jwt = true

[functions.social-metrics]
verify_jwt = true

[functions.fetch-release-metrics]
verify_jwt = true

[functions.spotify-for-artists-oauth]
verify_jwt = true

[functions.spotify-for-artists-metrics]
verify_jwt = true

[functions.landerzap-send]
verify_jwt = true
